### ISSUE TITLE
[Q] about gBot license

### ISSUE THREAD

**Issue by ghost** [ndee85/gBot#3]
Hey Andreas,

I was just curious if I could use your gBot textures in a game I'm making? It's going to be free to play, but with microtransactions (stash tabs, buy inventory slots, etc).  Not going to be selling anything that has to do with your textures. Just using it for the main character to move around

I will give credit in our credits page obviously too. But just wanted to double check, thanks in advance

**Comment by ndee85** [comment]
Hey there,
I have no problem with you using the textures of gBot.
Giving credit would be great!

**Comment by ghost** [comment]
Awesome @ndee85. Btw, love your animation and rigging tutorials they help so much. I will close now I guess ahah
